### ISSUE TITLE
Linux binary works only on quite recent distributions

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/GameController3#37]
In fact I haven't tested it on any other distribution than Linux Mint 21 (~ Ubuntu 22.04). Rudi reported that it doesn't work on Ubuntu 20.04. You can report further working / not-working distributions here. A solution can be to provide a simple command line server that serves the frontend and a web socket API (that would have a few more advantages than just reducing dependencies), but that is likely not going to happen before RoboCup 2023.

**Comment by jayenashar** [comment]
if you build the release on an old ubuntu with an old glibc i think it should work

**Comment by jayenashar** [comment]
> It is known that the provided Linux binaries do not work on Ubuntu 20.04. You can report working / not-working distributions in https://github.com/RoboCup-SPL/GameController3/issues/37 or via email to Arne Hasselbring.

not working on debian 11 with glibc 2.31

**Comment by ahasselbring** [comment]
The CI-built binaries should support glibc>=2.28 (e.g. Ubuntu >=18.10 and Debian >=10, but still not Ubuntu 18.04).

**Comment by jayenashar** [comment]
![image](https://github.com/RoboCup-SPL/GameController3/assets/1137152/7eaf77ec-83d5-419c-889d-0bd29d5681bd)
the draft is not published so i can't test on my system.

could you support 18.04 by changing https://github.com/RoboCup-SPL/GameController3/blob/master/.github/workflows/mkdist.yml#L18 ?  from the git history, it looks like you only tried 20.04

**Comment by ahasselbring** [comment]
rc.2 isn't released yet on purpose. The latest build is available at https://github.com/RoboCup-SPL/GameController3/suites/13735406684/artifacts/760207080 (I don't know if you need special privileges to access that link, at least I can't download it without being logged in).

The 18.04 runner image is deprecated and should have been removed in April, according to GitHub.

**Comment by jayenashar** [comment]
thanks that works.  for some reason i thought the CI/CD would only run on a tag/release and i didn't check the actions.

works on debian 11.  i guess if we need 18.04 support we can try a static build or the a [non-runner base image](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-hub-action).
