### ISSUE TITLE
package-lock.json should be committed to git

### ISSUE THREAD

**Issue by jayenashar** [RoboCup-SPL/GameController3#38]
this ensures that npm installs the same version of packages for everyone.  people should use `npm ci` when creating a production build instead of `npm install`.

(i use yarn not npm or i'd submit a PR)

**Comment by ahasselbring** [comment]
Yeah, this is part of what I meant by #13.

**Comment by jayenashar** [comment]
oh i saw that issue but only saw cargo mentioned so i skipped it
