### ISSUE TITLE
Can't build with time crate greater than v0.3.23

### ISSUE THREAD

**Issue by control13** [RoboCup-SPL/GameController3#50]
The build of the gamecontroller breaks, when the time create is newer than v0.3.23
With the newer version I get this building error:
```
Compiling game_controller_core v1.0.0-rc.2 (/home/tobias/nao/newGC/GameController3/game_controller_core)
error: to use a constant of type `deranged::ranged_i32::RangedI32<-999999999, 999999999>` in a pattern, `deranged::ranged_i32::RangedI32<-999999999, 999999999>` must be annotated with `#[derive(PartialEq, Eq)]`
   --> game_controller_core/src/timer.rs:155:26
    |
155 |                         (SignedDuration::ZERO, BehaviorAtZero::Clip)
    |                          ^^^^^^^^^^^^^^^^^^^^
    |
    = note: the traits must be derived, manual `impl`s are not sufficient
    = note: see https://doc.rust-lang.org/stable/std/marker/trait.StructuralEq.html for details

error: could not compile `game_controller_core` (lib) due to previous error
```

My current hotfix is to pin the time crate in the main Cargo.toml
`time = { version = "=0.3.23", features = ["formatting", "local-offset", "macros", "serde"] }`
and everthing works fine.

I tested it on ArchLinux and on Ubunut with both the newest rust compiler (v1.72.1)

**Comment by ahasselbring** [comment]
Hi and thanks for reporting this issue, at least for me [d355b83](https://github.com/RoboCup-SPL/GameController3/commit/d355b836d9d73936b1f6296c057cd99dfc3ebfc9) fixed it.
