### ISSUE TITLE
Register the list of robots on the team.

### ISSUE THREAD

**Issue by Hardest12345** [RoboCup-SPL/GameController3#55]
![Screenshot 2024-06-11 122032](https://github.com/RoboCup-SPL/GameController3/assets/143243211/8c19dbf2-f944-4f96-bcc9-7b1288280e97)

I have tried this game controller, but I have one confusion: how do we register the robot we own on the game controller to one of our chosen teams and not be registered on two teams? Since there are two teams, I want to conduct a test

**Comment by ahasselbring** [comment]
What do you mean by registering a robot?

The GameController broadcasts a message with the game state to all robots. A robot has to know its own team number (I suppose you know what that means as you have modified the configuration for a "Test" team) and player number to extract the data that are relevant for it. Each robot should periodically reply to the GameController with its team number and player number (as defined in the `RoboCupGameControlReturnData` struct), and that changes the color of the circle on the respective button from red to green. This means that it is up to the software on the robot how it identifies towards the GameController.

**Comment by Hardest12345** [comment]
Thank you for your response, ahasselbring. I appreciate your input. I understand that it is the software on the robot that determines how it identifies with the GameController. Would you happen to have a reference code that could provide further insight into how the robot can communicate with the game controller?
just for your information the robot that i used is Robotis-OP3
thank you, i'm sorry for my bad english.

**Comment by ahasselbring** [comment]
This GameController is only used for the Standard Platform League which plays with NAO robots. The Humanoid League uses this one: https://github.com/RoboCup-Humanoid-TC/GameController. They have an example Python client: https://github.com/RoboCup-Humanoid-TC/GameController/blob/master/protocols/python/receiver.py

**Comment by Hardest12345** [comment]
Thank you very much, Ahasselbring, for providing me with the information. i appreciate your help.
